## Advanced Indexing

Advanced indexing is triggered when the selection object, obj, is a non-tuple sequence object, an ndarray (of data type integer or bool), or a tuple with at least one sequence object or ndarray (of data type integer or bool). There are two types of advanced indexing: integer and Boolean.

Advanced indexing always returns a copy of the data (contrast with basic slicing that returns a view).


<hr>

The definition of advanced indexing means that x[(1, 2, 3),] is fundamentally different than x[(1, 2, 3)]. The latter is equivalent to x[1, 2, 3] which will trigger basic selection while the former will trigger advanced indexing. Be sure to understand why this occurs.

<hr>


In [51]:
import numpy as np

### Integer array indexing

Integer array indexing allows selection of arbitrary items in the array based on their N-dimensional index. Each integer array represents a number of indices into that dimension.

Negative values are permitted in the index arrays and work as they do with single indices or slices:


In [52]:
x = np.arange(10, 0, -1)

print(x)

print(x[np.array([3, 3, 1, 8])])
# ===
print(x[[3, 3, 1, 8]])

print(x[[3, 3, -3, 8]])

[10  9  8  7  6  5  4  3  2  1]
[7 7 9 2]
[7 7 9 2]
[7 7 3 2]


Indexing with multidimensional index arrays tend to be more unusual uses, but they are permitted, and they are useful for some problems.


In [53]:
x = np.reshape(np.arange(1, 11), (2, 5))

print(x)
print(x[[0]])
print(x[[0, 1]])
print(x[[0, 0, 1], [0, -1, -1]])
print(x[[0, 0, 1], 0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3 4 5]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  5 10]
[1 1 6]
