In [58]:
import numpy as np

In [64]:
l1 = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 0]

a1 = np.array(l1)
a2 = np.array(l2)
a3 = np.array([[1],
               [2]])

## Addition (+)


In [68]:
# Concate lists
print(l1 + l2)

# Array addition
print(a1 + 2)
print(a1 + a2)
print(a1 + a3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[3 4 5 6 7]
[ 7  9 11 13  5]
[[2 3 4 5 6]
 [3 4 5 6 7]]


## Subtraction (-)


In [66]:
# Array subtraction
print(a1 - 2)
print(a1 - a2)
print(a1 - a3)

[-1  0  1  2  3]
[-5 -5 -5 -5  5]
[[ 0  1  2  3  4]
 [-1  0  1  2  3]]


## Multiplication (\*)


In [69]:
# Repeat elements
print(l1 * 2)

# Array multiplication
print(a1 * 2)
print(a1 * a2)
print(a1 * a3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[ 6 14 24 36  0]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]


## Division (/)


In [70]:
# Array division
print(a1 / 2)
print(a1 / a2)
print(a1 / a3)

[0.5 1.  1.5 2.  2.5]
[0.16666667 0.28571429 0.375      0.44444444        inf]
[[1.  2.  3.  4.  5. ]
 [0.5 1.  1.5 2.  2.5]]


/tmp/ipykernel_14719/644241156.py:3: RuntimeWarning: divide by zero encountered in divide
  print(a1 / a2)


## Square Root


In [75]:
# Array square root
print(a1 ** 0.5)
print(np.sqrt(a1))

print(a3 ** 0.5)
print(np.sqrt(a3))

[1.         1.41421356 1.73205081 2.         2.23606798]
[1.         1.41421356 1.73205081 2.         2.23606798]
[[1.        ]
 [1.41421356]]
[[1.        ]
 [1.41421356]]


## Trigonometry


In [86]:
print(np.sin(a1))
print(np.cos(a1))
print(np.tan(a1))

print(np.sin(a3))
print(np.cos(a3))
print(np.tan(a3))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
[[0.84147098]
 [0.90929743]]
[[ 0.54030231]
 [-0.41614684]]
[[ 1.55740772]
 [-2.18503986]]


## Others


In [79]:
# Array square root
print(np.arctan(a1))
print(np.exp(a1))
print(np.log(a1))
print(np.log2(a3))
print(np.log10(a3))

# Plus many other operations

[0.78539816 1.10714872 1.24904577 1.32581766 1.37340077]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[[0.]
 [1.]]
[[0.     ]
 [0.30103]]


## **Summary**

Whenever you have NumPy Arrays which you can think of as vectors or matrices, then we can do the respective calculation in Python the same as the real world mathematics.
