In [1]:
import numpy as np

### numpy.full


In [2]:
full = np.full((2, 3), 5)

print(full.dtype)
print(full)

int64
[[5 5 5]
 [5 5 5]]


### numpy.zeros


In [3]:
# Auto fill with zeros
# zeros = np.zeros((2, 3)) # Float dtype by default

zeros = np.full((2, 3), 0, dtype=np.int16)
# ===
zeros = np.zeros((2, 3), dtype=np.int16)


print(zeros.dtype)
print(zeros)

int16
[[0 0 0]
 [0 0 0]]


### numpy.empty

Alocate memories for the array, while np.zeros assign its values to zeros

> It's a bit faster than np.zeros, but each element has default value


In [4]:
empty = np.empty((2, 3), dtype=np.int32)


print(empty.dtype)
print(empty)
print(empty[0, 0])

int32
[[12376     0     0]
 [    0    32     0]]
12376


### numpy.arange


In [5]:
arange = np.arange(1, 11)
arange2 = np.arange(1, 11, 2, dtype=np.float64)

print(arange.dtype)
print(arange)

print(arange2.dtype)
print(arange2)

int64
[ 1  2  3  4  5  6  7  8  9 10]
float64
[1. 3. 5. 7. 9.]


### numpy.linspace


In [17]:
linspace = np.linspace(1, 10, 10)
linspace2 = np.linspace(1, 10, 4)

print(linspace.dtype)
print(linspace)

print(linspace2.dtype)
print(linspace2)

float64
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64
[ 1.  4.  7. 10.]
