# Indexing on ndarrays


ndarrays can be indexed using the standard Python x[obj] syntax, where x is the array and obj the selection. There are different kinds of indexing available depending on obj: basic indexing, advanced indexing and field access.


Note that in Python, `x[(exp1, exp2, ..., expN)]` is equivalent to `x[exp1, exp2, ..., expN]`; the latter is just syntactic sugar for the former.


In [149]:
import numpy as np

### Single element indexing

Single element indexing works exactly like that for other standard Python sequences. It is 0-based, and accepts negative indices for indexing from the end of the array.


In [150]:
x = np.arange(10)

print('x:', x)
print('x[1]:', x[1])
print('x[-1]:', x[-1])

x: [0 1 2 3 4 5 6 7 8 9]
x[1]: 1
x[-1]: 9


In [151]:
x = np.reshape(x, (2, 5))  # == x.shape = (2, 5)

print('x:', x)
print('x[0]:', x[0])
print('x[0, -2]:', x[0, -2])  # == x[(0, -2)]
print('x[0][-2]:', x[0][-2])

x: [[0 1 2 3 4]
 [5 6 7 8 9]]
x[0]: [0 1 2 3 4]
x[0, -2]: 3
x[0][-2]: 3


Note that `x[0, -2] == x[0][-2]` though the second case is more inefficient as a new temporary array is created after the first index that is subsequently indexed by 2.


### Slicing and striding

Basic slicing extends Python’s basic concept of slicing to N dimensions. Basic slicing occurs when obj is a `slice` object (constructed by `start:stop:step` notation inside of brackets), an `integer`, or a `tuple of slice objects and integers`. `Ellipsis` and `newaxis` objects can be interspersed with these as well.


In [152]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print('x[1:7:2]:', x[1:7:2])
print('\n'+'='*20)
print('x[slice(-2, None, None)]:', x[slice(-2, None, None)])
# ===
print('x[slice(-2, None)]:', x[slice(-2, None)])
# ===
print('x[-2:]:', x[-2:])
# ===
print('x[-2:10]:', x[-2:10])
print('='*20+'\n')
print('x[-3:3:-1]:', x[-3:3:-1])  # == x[-2:]

x[1:7:2]: [1 3 5]

x[slice(-2, None, None)]: [8 9]
x[slice(-2, None)]: [8 9]
x[-2:]: [8 9]
x[-2:10]: [8 9]

x[-3:3:-1]: [7 6 5 4]


### Dimensional indexing tools

There are some tools to facilitate the easy matching of array shapes with expressions and in assignments.


`Ellipsis` expands to the number of `:` objects needed for the selection tuple to index all dimensions. In most cases, this means that the length of the expanded selection tuple is `x.ndim`. There may only be a single ellipsis present.


In [153]:
x = np.array([
    [
        [1], [2], [3]
    ],
    [
        [4], [5], [6]
    ]
])

print('x[:, :, 0]:\n', x[:, :, 0])
print('='*20)
print('x[..., 0]:\n', x[..., 0])

x[:, :, 0]:
 [[1 2 3]
 [4 5 6]]
x[..., 0]:
 [[1 2 3]
 [4 5 6]]


Each `newaxis` object in the selection tuple serves to expand the dimensions of the resulting selection by one unit-length dimension. The added dimension is the position of the `newaxis` object in the selection tuple. `newaxis` is an alias for `None`, and `None` can be used in place of this with the same result.

So.. `np.newaxis` the same as `None`


In [154]:
print('x[:, np.newaxis, :, :].shape:', x[:, np.newaxis, :, :].shape)
print('='*20)
print('np.reshape(x, (2, 1, 3, 1)).shape:', np.reshape(x, (2, 1, 3, 1)).shape)
print('='*20)
print('x[:, None, :, :].shape:', x[:, None, :, :].shape)

x[:, np.newaxis, :, :].shape: (2, 1, 3, 1)
np.reshape(x, (2, 1, 3, 1)).shape: (2, 1, 3, 1)
x[:, None, :, :].shape: (2, 1, 3, 1)


This can be handy to combine two arrays in a way that otherwise would require explicit reshaping operations. For example:


In [155]:
x = np.arange(5)
print('x[:, np.newaxis] + x[np.newaxis, :]:\n',
      x[:, np.newaxis] + x[np.newaxis, :])

x[:, np.newaxis] + x[np.newaxis, :]:
 [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
