In [114]:
import numpy as np

In [115]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
y = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

display(x)
display(y)

array([[1, 2, 3],
       [4, 5, 6]])

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#### Append

**Axis parameter:**

- Axis None (Default): Flatten the input array and append the new data as a flattened array
- Axis 0: Refers to the 1st dimension (rows in a 2D array).
- Axis 1: Refers to the 2nd dimension (columns in a 2D array).
- Axis 2: Refers to the 3rd dimension, and so on.


In [116]:
a = np.append(x, [0, 0, 0], axis=None)  # Axis is None by default

b = np.append(x, [[17, 18, 19]], axis=0)
c = np.append(x, [[14], [17]], axis=1)

print(f'a:\n{a}\n')
print(f'b:\n{b}\n')
print(f'c:\n{c}\n')

a:
[1 2 3 4 5 6 0 0 0]

b:
[[ 1  2  3]
 [ 4  5  6]
 [17 18 19]]

c:
[[ 1  2  3 14]
 [ 4  5  6 17]]



In [117]:
d = np.append(y, [[[0, 0], [0, 0]]], axis=0)
e = np.append(y, [[[0, 0]], [[0, 0]]], axis=1)
f = np.append(y, [[[0], [0]], [[0], [0]]], axis=2)

print(f'd:\n{d}\n')
print(f'e:\n{e}\n')
print(f'f:\n{f}\n')

d:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[0 0]
  [0 0]]]

e:
[[[1 2]
  [3 4]
  [0 0]]

 [[5 6]
  [7 8]
  [0 0]]]

f:
[[[1 2 0]
  [3 4 0]]

 [[5 6 0]
  [7 8 0]]]

