# Numpy Array

Unlike Python List, NumPy Array can only have single data type for each of its element


In [58]:
import numpy as np


# Hard type its elements
array = np.array([1, 2, 3, '4', 5], dtype=np.str_)  # Convert to strings
# array = np.array([1, 2, 3, '4', 5], dtype='<U1')  # String max chars = 1

print(type(array))

# The data types of its elements
print(array.dtype)
print(type(array[0]))

print(array.size)  # Total elements

print()

print(array)
print(array[1])
print(array[1:])
print(array[1:3])
print(array[:-2])
print(array[1:-2])
print(array[-4:-2])

<class 'numpy.ndarray'>
<U1
<class 'numpy.str_'>
5

['1' '2' '3' '4' '5']
2
['2' '3' '4' '5']
['2' '3']
['1' '2' '3']
['2' '3']
['2' '3']


## Multidimensional NumPy Array

Multidimensional NumPy Array can only have the same length for each row


In [59]:
md_array = np.array([[1, 2, 3],
                     [4, 5, 6]])

print(type(md_array))
print(md_array.dtype)  # The data types of the elements
print(md_array.ndim)  # How deep the dimension is (The level of deepness)
print(md_array.size)  # Total elements
print(md_array.shape)

print(md_array)
print(md_array[0, 1])
print(md_array[0][1])

<class 'numpy.ndarray'>
int64
2
6
(2, 3)
[[1 2 3]
 [4 5 6]]
2
2


In [60]:
md_array_2 = np.array([[[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]],
                       [[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]]])

print(type(md_array_2))
print(md_array_2.ndim)  # How deep the dimension is
print(md_array_2.shape)
print(md_array_2)

<class 'numpy.ndarray'>
3
(2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
