In [26]:
import numpy as np

In [27]:
def print_array(label: str, arr: np.ndarray):
    print(label + ':', arr.shape, '\n', arr, '\n')

In [28]:
x = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

print_array('x', x)

x: (4, 5) 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 



#### Reshape


In [86]:
a = np.reshape(x, (5, 4))
b = np.reshape(x, (2, 10))
c = np.reshape(x, (10, 2))
# # ===
# # c = x.reshape(10, 2)

print_array('a', a)
print_array('b', b)
print_array('c', c)

a: (5, 4) 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] 

b: (2, 10) 
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]] 

c: (10, 2) 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]] 

