In [8]:
import numpy as np

In [9]:
def print_array(label: str, arr: np.ndarray):
    print(label + ':', arr.shape, '\n', arr, '\n')

In [10]:
x = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

print_array('x', x)

x: (4, 5) 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 



#### Reshape


In [11]:
a = np.reshape(x, (5, 4))
b = np.reshape(x, (2, 10))
c = np.reshape(x, (2, 2, 5))  # Will become a 3-dimensional array
# ===
# c = x.reshape(10, 2)

print_array('a', a)
print_array('b', b)
print_array('c', c)

a: (5, 4) 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] 

b: (2, 10) 
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]] 

c: (2, 2, 5) 
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]] 



**Order parameter**

{‘C’, ‘F’, ‘A’}, optional
Read the elements of a using this index order, and place the elements into the reshaped array using this index order. ‘C’ means to read / write the elements using C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest. ‘F’ means to read / write the elements using Fortran-like index order, with the first index changing fastest, and the last index changing slowest. Note that the ‘C’ and ‘F’ options take no account of the memory layout of the underlying array, and only refer to the order of indexing. ‘A’ means to read / write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.


In [12]:
a = np.reshape(x, 20)
# ===
# a = np.reshape(x, (20))
# ===
# a = np.reshape(x, (20,))
# ===
# a = x.reshape(20)

b = np.reshape(x, 20, order='A')
c = np.reshape(x, 20, order='C')
d = np.reshape(x, 20, order='F')
e = np.reshape(x, (2, 10), order='F')

print_array('a', a)
print_array('b', b)
print_array('c', c)
print_array('d', d)
print_array('e', e)

a: (20,) 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

b: (20,) 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

c: (20,) 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

d: (20,) 
 [ 1  6 11 16  2  7 12 17  3  8 13 18  4  9 14 19  5 10 15 20] 

e: (2, 10) 
 [[ 1 11  2 12  3 13  4 14  5 15]
 [ 6 16  7 17  8 18  9 19 10 20]] 



#### Resize

Return a new array with the specified shape.

If the new array is larger than the original array, then the new array is filled with repeated copies of a.

Note that this behavior is different from a.resize(new_shape) which fills with zeros instead of repeated copies of a.


In [13]:
a = np.resize(x, (2, 3))
b = np.resize(x, (6, 6))

print_array('x', x)
print_array('a', a)
print_array('b', b)

x: (4, 5) 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

a: (2, 3) 
 [[1 2 3]
 [4 5 6]] 

b: (6, 6) 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20  1  2  3  4]
 [ 5  6  7  8  9 10]
 [11 12 13 14 15 16]] 



#### Experiment resizing and filling arrays with zero

In here, I use np.resize instead of 'ndarray'.resize to manually filling it with zero (0)


In [14]:
def resize_and_fill_with_zero(arr: np.ndarray, shape: tuple):
    result = np.resize(arr, shape)
    start_index = arr.shape[0]*arr.shape[1]
    current_index = 0

    for i, y in enumerate(result):

        for j, z in enumerate(y):
            if current_index < start_index:
                current_index += 1
            else:
                result[i, j] = 0

    return result

In [15]:
ngetes = resize_and_fill_with_zero(x, (6, 6))

print_array('ngetes', ngetes)

ngetes: (6, 6) 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]] 

